version: '2'
services:
    app1-app:
        image: app1
        external_links:
            - app1-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/app1
    app1-postgresql:
        extends:
            file: postgresql.yml
            service: app1-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
