version: '2'
services:
    uaa-app:
        image: uaa
        external_links:
            - uaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/UAA
    uaa-postgresql:
        extends:
            file: postgresql.yml
            service: uaa-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
