version: '2'
services:
    uaa-app:
        image: uaa
        external_links:
            - uaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/uaa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        depends_on:
            - jhipster-registry
            - uaa-postgresql
    uaa-postgresql:
        container_name: uaa-postgresql
        extends:
            file: postgresql.yml
            service: postgresql
        environment:
            - POSTGRES_USER=uaa
            - POSTGRES_PASSWORD=
    foo-app:
        image: foo
        external_links:
            - foo-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/foo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        depends_on:
            - jhipster-registry
            - foo-postgresql
    foo-postgresql:
        container_name: foo-postgresql
        extends:
            file: postgresql.yml
            service: postgresql
        environment:
            - POSTGRES_USER=foo
            - POSTGRES_PASSWORD=
    bar-app:
        image: bar
        external_links:
            - bar-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/bar
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        depends_on:
            - jhipster-registry
            - bar-postgresql
    bar-postgresql:
        container_name: bar-postgresql
        extends:
            file: postgresql.yml
            service: postgresql
        environment:
            - POSTGRES_USER=bar
            - POSTGRES_PASSWORD=
    gateway-app:
        image: gateway
        external_links:
            - gateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gateway
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        depends_on:
            - jhipster-registry
            - gateway-postgresql
    gateway-postgresql:
        container_name: gateway-postgresql
        extends:
            file: postgresql.yml
            service: postgresql
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
