version: '2'
services:
    app1-app:
        image: app1
        external_links:
            - app1-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/app1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    app1-postgresql:
        extends:
            file: postgresql.yml
            service: app1-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
